---
all:
  children:
    k3s_cluster:
      children:
        server:
          hosts:
            mou-mini1:
              ansible_host: mou-mini1.oue.home
            mou-mini2:
              ansible_host: mou-mini2.oue.home
            mou-pc1:
              ansible_host: mou-pc1.oue.home
        agent:
          hosts:
            mou-pi5:
              ansible_host: mou-pi5.oue.home
            mou-mini3:
              ansible_host: mou-mini3.oue.home
            mou-mini4:
              ansible_host: mou-mini4.oue.home
            mou-mini5:
              ansible_host: mou-mini5.oue.home
  vars:
    ansible_port: 22
    ansible_user: ansible
    k3s_version: v1.34.6+k3s1
    # The token should be a random string of reasonable length. You can generate
    # one with the following commands:
    # - openssl rand -base64 64
    # - pwgen -s 64 1
    # You can use ansible-vault to encrypt this value / keep it secret.
    # Or you can omit it if not using Vagrant and let the first server automatically generate one.
    # token: "changeme!"
    api_endpoint: "cluster.oue.home"