# fetch-kubeconfig.yml
- hosts: mou-mini1
  become: true
  tasks:
    - ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env', 'HOME') }}/.kube/k3s-cluster.config"
        flat: true
