---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: betterstack-uptime
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mattyo161/homelab.git
    targetRevision: HEAD
    path: apps/betterstack/uptime
  destination:
    server: https://kubernetes.default.svc
    namespace: betterstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
