---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://headlamp-k8s.github.io/headlamp/
      chart: headlamp
      targetRevision: "0.25.0"
      helm:
        releaseName: headlamp
        valueFiles:
          - $values/apps/headlamp/values.yml
    - repoURL: https://github.com/mattyo161/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
